import product1 from '../assets/productsCLImage/product1.png'
import product2 from '../assets/productsCLImage/product2.png'
import product3 from '../assets/productsCLImage/product3.png'
import product4 from '../assets/productsCLImage/product4.png'
import product5 from '../assets/productsCLImage/product5.png'
import product6 from '../assets/productsCLImage/product6.png'
import product7 from '../assets/productsCLImage/product7.png'
import product8 from '../assets/productsCLImage/product8.png'
import product9 from '../assets/productsCLImage/product9.png'


export let productsList = [
    {
        id: 0,
        preview: product1,
        images: [product1],
        name: 'Barberton Daisy',
        price: '119.00',
        sku: '1995751877966',
        categories: 'Potter Plants',
        tags: ['Home', 'Garden', 'Plants'],
        sizes: ['S', 'M', 'L', 'XL'],
        shortDescription: 'The ceramic cylinder planters come with a wooden stand to help elevate your plants off the ground. The ceramic cylinder planters come with a wooden stand to help elevate your plants off the ground.',
        fullDescription: 'hello, now is not working'
    },
    {
        id: 1,
        preview: product2,
        images: [product2],
        name: 'Angel Wing Begonia',
        price: '169.00',
        sku: '1995751877966',
        categories: 'Potter Plants',
        tags: ['Home', 'Garden', 'Plants'],
        sizes: ['S', 'M', 'L', 'XL'],
        shortDescription: 'The ceramic cylinder planters come with a wooden stand to help elevate your plants off the ground. The ceramic cylinder planters come with a wooden stand to help elevate your plants off the ground.',
        fullDescription: 'hello, now is not working'
    },
    {
        id: 2,
        preview: product3,
        images: [product3],
        name: 'African Violet',
        priceWithoutDiscont: '229.00',
        discontSize: 13, // in procent
        price: '199.00',
        sku: '1995751877966',
        categories: 'Potter Plants',
        tags: ['Home', 'Garden', 'Plants'],
        sizes: ['S', 'M', 'L', 'XL'],
        shortDescription: 'The ceramic cylinder planters come with a wooden stand to help elevate your plants off the ground. The ceramic cylinder planters come with a wooden stand to help elevate your plants off the ground.',
        fullDescription: 'hello, now is not working'
    },
    {
        id: 3,
        preview: product4,
        images: [product4],
        name: 'Beach Spider Lily',
        price: '129.00',
        sku: '1995751877966',
        categories: 'Potter Plants',
        tags: ['Home', 'Garden', 'Plants'],
        sizes: ['S', 'M', 'L', 'XL'],
        shortDescription: 'The ceramic cylinder planters come with a wooden stand to help elevate your plants off the ground. The ceramic cylinder planters come with a wooden stand to help elevate your plants off the ground.',
        fullDescription: 'hello, now is not working'
    },
    {
        id: 4,
        preview: product5,
        images: [product5],
        name: 'Blushing Bromeliad',
        price: '139.00',
        sku: '1995751877966',
        categories: 'Potter Plants',
        tags: ['Home', 'Garden', 'Plants'],
        sizes: ['S', 'M', 'L', 'XL'],
        shortDescription: 'The ceramic cylinder planters come with a wooden stand to help elevate your plants off the ground. The ceramic cylinder planters come with a wooden stand to help elevate your plants off the ground.',
        fullDescription: 'hello, now is not working'
    },
    {
        id: 5,
        preview: product6,
        images: [product6],
        name: 'Aluminum Plant',
        price: '139.00',
        sku: '1995751877966',
        categories: 'Potter Plants',
        tags: ['Home', 'Garden', 'Plants'],
        sizes: ['S', 'M', 'L', 'XL'],
        shortDescription: 'The ceramic cylinder planters come with a wooden stand to help elevate your plants off the ground. The ceramic cylinder planters come with a wooden stand to help elevate your plants off the ground.',
        fullDescription: 'hello, now is not working'
    },
    {
        id: 6,
        preview: product7,
        images: [product7],
        name: 'Bird\'s Nest Fern',
        price: '99.00',
        sku: '1995751877966',
        categories: 'Potter Plants',
        tags: ['Home', 'Garden', 'Plants'],
        sizes: ['S', 'M', 'L', 'XL'],
        shortDescription: 'The ceramic cylinder planters come with a wooden stand to help elevate your plants off the ground. The ceramic cylinder planters come with a wooden stand to help elevate your plants off the ground.',
        fullDescription: 'hello, now is not working'
    },
    {
        id: 7,
        preview: product8,
        images: [product8],
        name: 'Broadleaf Lady Palm',
        price: '59.00',
        sku: '1995751877966',
        categories: 'Potter Plants',
        tags: ['Home', 'Garden', 'Plants'],
        sizes: ['S', 'M', 'L', 'XL'],
        shortDescription: 'The ceramic cylinder planters come with a wooden stand to help elevate your plants off the ground. The ceramic cylinder planters come with a wooden stand to help elevate your plants off the ground.',
        fullDescription: 'hello, now is not working'
    },
    {
        id: 8,
        preview: product9,
        images: [product9],
        name: 'Chinese Evergreen',
        price: '39.00',
        sku: '1995751877966',
        categories: 'Potter Plants',
        tags: ['Home', 'Garden', 'Plants'],
        sizes: ['S', 'M', 'L', 'XL'],
        shortDescription: 'The ceramic cylinder planters come with a wooden stand to help elevate your plants off the ground. The ceramic cylinder planters come with a wooden stand to help elevate your plants off the ground.',
        fullDescription: 'hello, now is not working'
    },
    {
        id: 9,
        preview: product1,
        images: [product1],
        name: 'Barberton Daisy',
        price: '119.00',
        sku: '1995751877966',
        categories: 'Potter Plants',
        tags: ['Home', 'Garden', 'Plants'],
        sizes: ['S', 'M', 'L', 'XL'],
        shortDescription: 'The ceramic cylinder planters come with a wooden stand to help elevate your plants off the ground. The ceramic cylinder planters come with a wooden stand to help elevate your plants off the ground.',
        fullDescription: 'hello, now is not working'
    },
    {
        id: 10,
        preview: product3,
        images: [product3],
        name: 'Beach Spider Lily',
        price: '129.00',
        sku: '1995751877966',
        categories: 'Potter Plants',
        tags: ['Home', 'Garden', 'Plants'],
        sizes: ['S', 'M', 'L', 'XL'],
        shortDescription: 'The ceramic cylinder planters come with a wooden stand to help elevate your plants off the ground. The ceramic cylinder planters come with a wooden stand to help elevate your plants off the ground.',
        fullDescription: 'hello, now is not working'
    },
    {
        id: 11,
        preview: product1,
        images: [product1],
        name: 'Barberton Daisy',
        price: '119.00',
        sku: '1995751877966',
        categories: 'Potter Plants',
        tags: ['Home', 'Garden', 'Plants'],
        sizes: ['S', 'M', 'L', 'XL'],
        shortDescription: 'The ceramic cylinder planters come with a wooden stand to help elevate your plants off the ground. The ceramic cylinder planters come with a wooden stand to help elevate your plants off the ground.',
        fullDescription: 'hello, now is not working'
    },
    {
        id: 12,
        preview: product3,
        images: [product3],
        name: 'Beach Spider Lily',
        price: '129.00',
        sku: '1995751877966',
        categories: 'Potter Plants',
        tags: ['Home', 'Garden', 'Plants'],
        sizes: ['S', 'M', 'L', 'XL'],
        shortDescription: 'The ceramic cylinder planters come with a wooden stand to help elevate your plants off the ground. The ceramic cylinder planters come with a wooden stand to help elevate your plants off the ground.',
        fullDescription: 'hello, now is not working'
    },
    {
        id: 13,
        preview: product1,
        images: [product1],
        name: 'Barberton Daisy',
        price: '119.00',
        sku: '1995751877966',
        categories: 'Potter Plants',
        tags: ['Home', 'Garden', 'Plants'],
        sizes: ['S', 'M', 'L', 'XL'],
        shortDescription: 'The ceramic cylinder planters come with a wooden stand to help elevate your plants off the ground. The ceramic cylinder planters come with a wooden stand to help elevate your plants off the ground.',
        fullDescription: 'hello, now is not working'
    },
    {
        id: 14,
        preview: product3,
        images: [product3],
        name: 'Beach Spider Lily',
        price: '129.00',
        sku: '1995751877966',
        categories: 'Potter Plants',
        tags: ['Home', 'Garden', 'Plants'],
        sizes: ['S', 'M', 'L', 'XL'],
        shortDescription: 'The ceramic cylinder planters come with a wooden stand to help elevate your plants off the ground. The ceramic cylinder planters come with a wooden stand to help elevate your plants off the ground.',
        fullDescription: 'hello, now is not working'
    },
    {
        id: 15,
        preview: product1,
        images: [product1],
        name: 'Barberton Daisy',
        price: '119.00',
        sku: '1995751877966',
        categories: 'Potter Plants',
        tags: ['Home', 'Garden', 'Plants'],
        sizes: ['S', 'M', 'L', 'XL'],
        shortDescription: 'The ceramic cylinder planters come with a wooden stand to help elevate your plants off the ground. The ceramic cylinder planters come with a wooden stand to help elevate your plants off the ground.',
        fullDescription: 'hello, now is not working'
    },
    {
        id: 16,
        preview: product3,
        images: [product3],
        name: 'Beach Spider Lily',
        price: '129.00',
        sku: '1995751877966',
        categories: 'Potter Plants',
        tags: ['Home', 'Garden', 'Plants'],
        sizes: ['S', 'M', 'L', 'XL'],
        shortDescription: 'The ceramic cylinder planters come with a wooden stand to help elevate your plants off the ground. The ceramic cylinder planters come with a wooden stand to help elevate your plants off the ground.',
        fullDescription: 'hello, now is not working'
    },
    {
        id: 17,
        preview: product1,
        images: [product1],
        name: 'Barberton Daisy',
        price: '119.00',
        sku: '1995751877966',
        categories: 'Potter Plants',
        tags: ['Home', 'Garden', 'Plants'],
        sizes: ['S', 'M', 'L', 'XL'],
        shortDescription: 'The ceramic cylinder planters come with a wooden stand to help elevate your plants off the ground. The ceramic cylinder planters come with a wooden stand to help elevate your plants off the ground.',
        fullDescription: 'hello, now is not working'
    },
    {
        id: 18,
        preview: product3,
        images: [product3],
        name: 'Beach Spider Lily',
        price: '129.00',
        sku: '1995751877966',
        categories: 'Potter Plants',
        tags: ['Home', 'Garden', 'Plants'],
        sizes: ['S', 'M', 'L', 'XL'],
        shortDescription: 'The ceramic cylinder planters come with a wooden stand to help elevate your plants off the ground. The ceramic cylinder planters come with a wooden stand to help elevate your plants off the ground.',
        fullDescription: 'hello, now is not working'
    },
    {
        id: 19,
        preview: product1,
        images: [product1],
        name: 'Barberton Daisy',
        price: '119.00',
        sku: '1995751877966',
        categories: 'Potter Plants',
        tags: ['Home', 'Garden', 'Plants'],
        sizes: ['S', 'M', 'L', 'XL'],
        shortDescription: 'The ceramic cylinder planters come with a wooden stand to help elevate your plants off the ground. The ceramic cylinder planters come with a wooden stand to help elevate your plants off the ground.',
        fullDescription: 'hello, now is not working'
    },
    {
        id: 20,
        preview: product3,
        images: [product3],
        name: 'Beach Spider Lily',
        price: '129.00',
        sku: '1995751877966',
        categories: 'Potter Plants',
        tags: ['Home', 'Garden', 'Plants'],
        sizes: ['S', 'M', 'L', 'XL'],
        shortDescription: 'The ceramic cylinder planters come with a wooden stand to help elevate your plants off the ground. The ceramic cylinder planters come with a wooden stand to help elevate your plants off the ground.',
        fullDescription: 'hello, now is not working'
    },
    {
        id: 21,
        preview: product1,
        images: [product1],
        name: 'Barberton Daisy',
        price: '119.00',
        sku: '1995751877966',
        categories: 'Potter Plants',
        tags: ['Home', 'Garden', 'Plants'],
        sizes: ['S', 'M', 'L', 'XL'],
        shortDescription: 'The ceramic cylinder planters come with a wooden stand to help elevate your plants off the ground. The ceramic cylinder planters come with a wooden stand to help elevate your plants off the ground.',
        fullDescription: 'hello, now is not working'
    },
    {
        id: 22,
        preview: product3,
        images: [product3],
        name: 'Beach Spider Lily',
        price: '129.00',
        sku: '1995751877966',
        categories: 'Potter Plants',
        tags: ['Home', 'Garden', 'Plants'],
        sizes: ['S', 'M', 'L', 'XL'],
        shortDescription: 'The ceramic cylinder planters come with a wooden stand to help elevate your plants off the ground. The ceramic cylinder planters come with a wooden stand to help elevate your plants off the ground.',
        fullDescription: 'hello, now is not working'
    },
    {
        id: 23,
        preview: product1,
        images: [product1],
        name: 'Barberton Daisy',
        price: '119.00',
        sku: '1995751877966',
        categories: 'Potter Plants',
        tags: ['Home', 'Garden', 'Plants'],
        sizes: ['S', 'M', 'L', 'XL'],
        shortDescription: 'The ceramic cylinder planters come with a wooden stand to help elevate your plants off the ground. The ceramic cylinder planters come with a wooden stand to help elevate your plants off the ground.',
        fullDescription: 'hello, now is not working'
    },
    {
        id: 24,
        preview: product3,
        images: [product3],
        name: 'Beach Spider Lily',
        price: '129.00',
        sku: '1995751877966',
        categories: 'Potter Plants',
        tags: ['Home', 'Garden', 'Plants'],
        sizes: ['S', 'M', 'L', 'XL'],
        shortDescription: 'The ceramic cylinder planters come with a wooden stand to help elevate your plants off the ground. The ceramic cylinder planters come with a wooden stand to help elevate your plants off the ground.',
        fullDescription: 'hello, now is not working'
    },
    {
        id: 25,
        preview: product1,
        images: [product1],
        name: 'Barberton Daisy',
        price: '119.00',
        sku: '1995751877966',
        categories: 'Potter Plants',
        tags: ['Home', 'Garden', 'Plants'],
        sizes: ['S', 'M', 'L', 'XL'],
        shortDescription: 'The ceramic cylinder planters come with a wooden stand to help elevate your plants off the ground. The ceramic cylinder planters come with a wooden stand to help elevate your plants off the ground.',
        fullDescription: 'hello, now is not working'
    },
    {
        id: 26,
        preview: product3,
        images: [product3],
        name: 'Beach Spider Lily',
        price: '129.00',
        sku: '1995751877966',
        categories: 'Potter Plants',
        tags: ['Home', 'Garden', 'Plants'],
        sizes: ['S', 'M', 'L', 'XL'],
        shortDescription: 'The ceramic cylinder planters come with a wooden stand to help elevate your plants off the ground. The ceramic cylinder planters come with a wooden stand to help elevate your plants off the ground.',
        fullDescription: 'hello, now is not working'
    },
    {
        id: 27,
        preview: product3,
        images: [product3],
        name: 'Beach Spider Lily',
        price: '129.00',
        sku: '1995751877966',
        categories: 'Potter Plants',
        tags: ['Home', 'Garden', 'Plants'],
        sizes: ['S', 'M', 'L', 'XL'],
        shortDescription: 'The ceramic cylinder planters come with a wooden stand to help elevate your plants off the ground. The ceramic cylinder planters come with a wooden stand to help elevate your plants off the ground.',
        fullDescription: 'hello, now is not working'
    },
    {
        id: 28,
        preview: product3,
        images: [product3],
        name: 'Beach Spider Lily',
        price: '129.00',
        sku: '1995751877966',
        categories: 'Potter Plants',
        tags: ['Home', 'Garden', 'Plants'],
        sizes: ['S', 'M', 'L', 'XL'],
        shortDescription: 'The ceramic cylinder planters come with a wooden stand to help elevate your plants off the ground. The ceramic cylinder planters come with a wooden stand to help elevate your plants off the ground.',
        fullDescription: 'hello, now is not working'
    },
    {
        id: 29,
        preview: product3,
        images: [product3],
        name: 'Beach Spider Lily',
        price: '129.00',
        sku: '1995751877966',
        categories: 'Potter Plants',
        tags: ['Home', 'Garden', 'Plants'],
        sizes: ['S', 'M', 'L', 'XL'],
        shortDescription: 'The ceramic cylinder planters come with a wooden stand to help elevate your plants off the ground. The ceramic cylinder planters come with a wooden stand to help elevate your plants off the ground.',
        fullDescription: 'hello, now is not working'
    },
    {
        id: 30,
        preview: product3,
        images: [product3],
        name: 'Beach Spider Lily',
        price: '129.00',
        sku: '1995751877966',
        categories: 'Potter Plants',
        tags: ['Home', 'Garden', 'Plants'],
        sizes: ['S', 'M', 'L', 'XL'],
        shortDescription: 'The ceramic cylinder planters come with a wooden stand to help elevate your plants off the ground. The ceramic cylinder planters come with a wooden stand to help elevate your plants off the ground.',
        fullDescription: 'hello, now is not working'
    },
    {
        id: 31,
        preview: product3,
        images: [product3],
        name: 'Beach Spider Lily',
        price: '129.00',
        sku: '1995751877966',
        categories: 'Potter Plants',
        tags: ['Home', 'Garden', 'Plants'],
        sizes: ['S', 'M', 'L', 'XL'],
        shortDescription: 'The ceramic cylinder planters come with a wooden stand to help elevate your plants off the ground. The ceramic cylinder planters come with a wooden stand to help elevate your plants off the ground.',
        fullDescription: 'hello, now is not working'
    },
    {
        id: 32,
        preview: product3,
        images: [product3],
        name: 'Beach Spider Lily',
        price: '129.00',
        sku: '1995751877966',
        categories: 'Potter Plants',
        tags: ['Home', 'Garden', 'Plants'],
        sizes: ['S', 'M', 'L', 'XL'],
        shortDescription: 'The ceramic cylinder planters come with a wooden stand to help elevate your plants off the ground. The ceramic cylinder planters come with a wooden stand to help elevate your plants off the ground.',
        fullDescription: 'hello, now is not working'
    },
    {
        id: 33,
        preview: product3,
        images: [product3],
        name: 'Beach Spider Lily',
        price: '129.00',
        sku: '1995751877966',
        categories: 'Potter Plants',
        tags: ['Home', 'Garden', 'Plants'],
        sizes: ['S', 'M', 'L', 'XL'],
        shortDescription: 'The ceramic cylinder planters come with a wooden stand to help elevate your plants off the ground. The ceramic cylinder planters come with a wooden stand to help elevate your plants off the ground.',
        fullDescription: 'hello, now is not working'
    },
    {
        id: 34,
        preview: product3,
        images: [product3],
        name: 'Beach Spider Lily',
        price: '129.00',
        sku: '1995751877966',
        categories: 'Potter Plants',
        tags: ['Home', 'Garden', 'Plants'],
        sizes: ['S', 'M', 'L', 'XL'],
        shortDescription: 'The ceramic cylinder planters come with a wooden stand to help elevate your plants off the ground. The ceramic cylinder planters come with a wooden stand to help elevate your plants off the ground.',
        fullDescription: 'hello, now is not working'
    },
    {
        id: 35,
        preview: product3,
        images: [product3],
        name: 'Beach Spider Lily',
        price: '129.00',
        sku: '1995751877966',
        categories: 'Potter Plants',
        tags: ['Home', 'Garden', 'Plants'],
        sizes: ['S', 'M', 'L', 'XL'],
        shortDescription: 'The ceramic cylinder planters come with a wooden stand to help elevate your plants off the ground. The ceramic cylinder planters come with a wooden stand to help elevate your plants off the ground.',
        fullDescription: 'hello, now is not working'
    },
    {
        id: 36,
        preview: product3,
        images: [product3],
        name: 'Beach Spider Lily',
        price: '129.00',
        sku: '1995751877966',
        categories: 'Potter Plants',
        tags: ['Home', 'Garden', 'Plants'],
        sizes: ['S', 'M', 'L', 'XL'],
        shortDescription: 'The ceramic cylinder planters come with a wooden stand to help elevate your plants off the ground. The ceramic cylinder planters come with a wooden stand to help elevate your plants off the ground.',
        fullDescription: 'hello, now is not working'
    },
    {
        id: 37,
        preview: product3,
        images: [product3],
        name: 'Beach Spider Lily',
        price: '129.00',
        sku: '1995751877966',
        categories: 'Potter Plants',
        tags: ['Home', 'Garden', 'Plants'],
        sizes: ['S', 'M', 'L', 'XL'],
        shortDescription: 'The ceramic cylinder planters come with a wooden stand to help elevate your plants off the ground. The ceramic cylinder planters come with a wooden stand to help elevate your plants off the ground.',
        fullDescription: 'hello, now is not working'
    },
    {
        id: 38,
        preview: product3,
        images: [product3],
        name: 'Beach Spider Lily',
        price: '129.00',
        sku: '1995751877966',
        categories: 'Potter Plants',
        tags: ['Home', 'Garden', 'Plants'],
        sizes: ['S', 'M', 'L', 'XL'],
        shortDescription: 'The ceramic cylinder planters come with a wooden stand to help elevate your plants off the ground. The ceramic cylinder planters come with a wooden stand to help elevate your plants off the ground.',
        fullDescription: 'hello, now is not working'
    },
    {
        id: 39,
        preview: product3,
        images: [product3],
        name: 'Beach Spider Lily',
        price: '129.00',
        sku: '1995751877966',
        categories: 'Potter Plants',
        tags: ['Home', 'Garden', 'Plants'],
        sizes: ['S', 'M', 'L', 'XL'],
        shortDescription: 'The ceramic cylinder planters come with a wooden stand to help elevate your plants off the ground. The ceramic cylinder planters come with a wooden stand to help elevate your plants off the ground.',
        fullDescription: 'hello, now is not working'
    },
    {
        id: 40,
        preview: product3,
        images: [product3],
        name: 'Beach Spider Lily',
        price: '129.00',
        sku: '1995751877966',
        categories: 'Potter Plants',
        tags: ['Home', 'Garden', 'Plants'],
        sizes: ['S', 'M', 'L', 'XL'],
        shortDescription: 'The ceramic cylinder planters come with a wooden stand to help elevate your plants off the ground. The ceramic cylinder planters come with a wooden stand to help elevate your plants off the ground.',
        fullDescription: 'hello, now is not working'
    },
    {
        id: 41,
        preview: product3,
        images: [product3],
        name: 'Beach Spider Lily',
        price: '129.00',
        sku: '1995751877966',
        categories: 'Potter Plants',
        tags: ['Home', 'Garden', 'Plants'],
        sizes: ['S', 'M', 'L', 'XL'],
        shortDescription: 'The ceramic cylinder planters come with a wooden stand to help elevate your plants off the ground. The ceramic cylinder planters come with a wooden stand to help elevate your plants off the ground.',
        fullDescription: 'hello, now is not working'
    },
    {
        id: 42,
        preview: product3,
        images: [product3],
        name: 'Beach Spider Lily',
        price: '129.00',
        sku: '1995751877966',
        categories: 'Potter Plants',
        tags: ['Home', 'Garden', 'Plants'],
        sizes: ['S', 'M', 'L', 'XL'],
        shortDescription: 'The ceramic cylinder planters come with a wooden stand to help elevate your plants off the ground. The ceramic cylinder planters come with a wooden stand to help elevate your plants off the ground.',
        fullDescription: 'hello, now is not working'
    },
    {
        id: 43,
        preview: product3,
        images: [product3],
        name: 'Beach Spider Lily',
        price: '129.00',
        sku: '1995751877966',
        categories: 'Potter Plants',
        tags: ['Home', 'Garden', 'Plants'],
        sizes: ['S', 'M', 'L', 'XL'],
        shortDescription: 'The ceramic cylinder planters come with a wooden stand to help elevate your plants off the ground. The ceramic cylinder planters come with a wooden stand to help elevate your plants off the ground.',
        fullDescription: 'hello, now is not working'
    },
    {
        id: 47,
        preview: product3,
        images: [product3],
        name: 'Beach Spider Lily',
        price: '129.00',
        sku: '1995751877966',
        categories: 'Potter Plants',
        tags: ['Home', 'Garden', 'Plants'],
        sizes: ['S', 'M', 'L', 'XL'],
        shortDescription: 'The ceramic cylinder planters come with a wooden stand to help elevate your plants off the ground. The ceramic cylinder planters come with a wooden stand to help elevate your plants off the ground.',
        fullDescription: 'hello, now is not working'
    },
    {
        id: 44,
        preview: product3,
        images: [product3],
        name: 'Beach Spider Lily',
        price: '129.00',
        sku: '1995751877966',
        categories: 'Potter Plants',
        tags: ['Home', 'Garden', 'Plants'],
        sizes: ['S', 'M', 'L', 'XL'],
        shortDescription: 'The ceramic cylinder planters come with a wooden stand to help elevate your plants off the ground. The ceramic cylinder planters come with a wooden stand to help elevate your plants off the ground.',
        fullDescription: 'hello, now is not working'
    },
    {
        id: 45,
        preview: product3,
        images: [product3],
        name: 'Beach Spider Lily',
        price: '129.00',
        sku: '1995751877966',
        categories: 'Potter Plants',
        tags: ['Home', 'Garden', 'Plants'],
        sizes: ['S', 'M', 'L', 'XL'],
        shortDescription: 'The ceramic cylinder planters come with a wooden stand to help elevate your plants off the ground. The ceramic cylinder planters come with a wooden stand to help elevate your plants off the ground.',
        fullDescription: 'hello, now is not working'
    },
    {
        id: 46,
        preview: product3,
        images: [product3],
        name: 'Beach Spider Lily',
        price: '129.00',
        sku: '1995751877966',
        categories: 'Potter Plants',
        tags: ['Home', 'Garden', 'Plants'],
        sizes: ['S', 'M', 'L', 'XL'],
        shortDescription: 'The ceramic cylinder planters come with a wooden stand to help elevate your plants off the ground. The ceramic cylinder planters come with a wooden stand to help elevate your plants off the ground.',
        fullDescription: 'hello, now is not working'
    },
    {
        id: 47,
        preview: product3,
        images: [product3],
        name: 'Beach Spider Lily',
        price: '129.00',
        sku: '1995751877966',
        categories: 'Potter Plants',
        tags: ['Home', 'Garden', 'Plants'],
        sizes: ['S', 'M', 'L', 'XL'],
        shortDescription: 'The ceramic cylinder planters come with a wooden stand to help elevate your plants off the ground. The ceramic cylinder planters come with a wooden stand to help elevate your plants off the ground.',
        fullDescription: 'hello, now is not working'
    },
    {
        id: 48,
        preview: product3,
        images: [product3],
        name: 'Beach Spider Lily',
        price: '129.00',
        sku: '1995751877966',
        categories: 'Potter Plants',
        tags: ['Home', 'Garden', 'Plants'],
        sizes: ['S', 'M', 'L', 'XL'],
        shortDescription: 'The ceramic cylinder planters come with a wooden stand to help elevate your plants off the ground. The ceramic cylinder planters come with a wooden stand to help elevate your plants off the ground.',
        fullDescription: 'hello, now is not working'
    },
    {
        id: 49,
        preview: product3,
        images: [product3],
        name: 'Beach Spider Lily',
        price: '129.00',
        sku: '1995751877966',
        categories: 'Potter Plants',
        tags: ['Home', 'Garden', 'Plants'],
        sizes: ['S', 'M', 'L', 'XL'],
        shortDescription: 'The ceramic cylinder planters come with a wooden stand to help elevate your plants off the ground. The ceramic cylinder planters come with a wooden stand to help elevate your plants off the ground.',
        fullDescription: 'hello, now is not working'
    },
    {
        id: 50,
        preview: product3,
        images: [product3],
        name: 'Beach Spider Lily',
        price: '129.00',
        sku: '1995751877966',
        categories: 'Potter Plants',
        tags: ['Home', 'Garden', 'Plants'],
        sizes: ['S', 'M', 'L', 'XL'],
        shortDescription: 'The ceramic cylinder planters come with a wooden stand to help elevate your plants off the ground. The ceramic cylinder planters come with a wooden stand to help elevate your plants off the ground.',
        fullDescription: 'hello, now is not working'
    },
    {
        id: 51,
        preview: product3,
        images: [product3],
        name: 'Beach Spider Lily',
        price: '129.00',
        sku: '1995751877966',
        categories: 'Potter Plants',
        tags: ['Home', 'Garden', 'Plants'],
        sizes: ['S', 'M', 'L', 'XL'],
        shortDescription: 'The ceramic cylinder planters come with a wooden stand to help elevate your plants off the ground. The ceramic cylinder planters come with a wooden stand to help elevate your plants off the ground.',
        fullDescription: 'hello, now is not working'
    },
    {
        id: 52,
        preview: product3,
        images: [product3],
        name: 'Beach Spider Lily',
        price: '129.00',
        sku: '1995751877966',
        categories: 'Potter Plants',
        tags: ['Home', 'Garden', 'Plants'],
        sizes: ['S', 'M', 'L', 'XL'],
        shortDescription: 'The ceramic cylinder planters come with a wooden stand to help elevate your plants off the ground. The ceramic cylinder planters come with a wooden stand to help elevate your plants off the ground.',
        fullDescription: 'hello, now is not working'
    },
    {
        id: 53,
        preview: product3,
        images: [product3],
        name: 'Beach Spider Lily',
        price: '129.00',
        sku: '1995751877966',
        categories: 'Potter Plants',
        tags: ['Home', 'Garden', 'Plants'],
        sizes: ['S', 'M', 'L', 'XL'],
        shortDescription: 'The ceramic cylinder planters come with a wooden stand to help elevate your plants off the ground. The ceramic cylinder planters come with a wooden stand to help elevate your plants off the ground.',
        fullDescription: 'hello, now is not working'
    },
    {
        id: 54,
        preview: product3,
        images: [product3],
        name: 'Beach Spider Lily',
        price: '129.00',
        sku: '1995751877966',
        categories: 'Potter Plants',
        tags: ['Home', 'Garden', 'Plants'],
        sizes: ['S', 'M', 'L', 'XL'],
        shortDescription: 'The ceramic cylinder planters come with a wooden stand to help elevate your plants off the ground. The ceramic cylinder planters come with a wooden stand to help elevate your plants off the ground.',
        fullDescription: 'hello, now is not working'
    },
    {
        id: 55,
        preview: product3,
        images: [product3],
        name: 'Beach Spider Lily',
        price: '129.00',
        sku: '1995751877966',
        categories: 'Potter Plants',
        tags: ['Home', 'Garden', 'Plants'],
        sizes: ['S', 'M', 'L', 'XL'],
        shortDescription: 'The ceramic cylinder planters come with a wooden stand to help elevate your plants off the ground. The ceramic cylinder planters come with a wooden stand to help elevate your plants off the ground.',
        fullDescription: 'hello, now is not working'
    },
    {
        id: 56,
        preview: product3,
        images: [product3],
        name: 'Beach Spider Lily',
        price: '129.00',
        sku: '1995751877966',
        categories: 'Potter Plants',
        tags: ['Home', 'Garden', 'Plants'],
        sizes: ['S', 'M', 'L', 'XL'],
        shortDescription: 'The ceramic cylinder planters come with a wooden stand to help elevate your plants off the ground. The ceramic cylinder planters come with a wooden stand to help elevate your plants off the ground.',
        fullDescription: 'hello, now is not working'
    },
    {
        id: 57,
        preview: product3,
        images: [product3],
        name: 'Beach Spider Lily',
        price: '129.00',
        sku: '1995751877966',
        categories: 'Potter Plants',
        tags: ['Home', 'Garden', 'Plants'],
        sizes: ['S', 'M', 'L', 'XL'],
        shortDescription: 'The ceramic cylinder planters come with a wooden stand to help elevate your plants off the ground. The ceramic cylinder planters come with a wooden stand to help elevate your plants off the ground.',
        fullDescription: 'hello, now is not working'
    },


]